### ISSUE TITLE
Thoughts on `PartialOrd` with std `f64`, `f32` and with other typed_floats

### ISSUE THREAD

**Issue by wcarmon** [tdelmas/typed_floats#101]
Please share your thoughts on these:

# Issue-1: comparing typed_floats to std `f64` or `f32`

Example:
```rust
let a: f64 = 0.1; // <-- pretend this is produced by some other lib
let b = PositiveFinite::try_from(0.2)?;

if a < b {    // <--- fails here
    println!("a is less, do some logic ...");
}
```

Simple workaround:
```rust
if a < b.into() {
   ...
```

The workaround is only a few chars, so it's a small inconvenience.  Though it could be more convenient, probably not worth a code change.

# Issue-2: Comparing to other typed_floats
This is more difficult ...

Example:
```rust
let a = StrictlyPositiveFinite::try_from(0.1)?;
let b = PositiveFinite::try_from(0.2)?;

if a < b {   // <--- fails here
    println!("a is less, do some logic ...");
}
```

logically, it seems we should be able to compare `StrictlyPositiveFinite` and `PositiveFinite`.

I think we would need something like:

```rust
impl PartialEq<StrictlyPositiveFinite> for PositiveFinite {
    fn eq(&self, other: &StrictlyPositiveFinite) -> bool {
        // TODO: compare the internal repr
    }
}

impl PartialOrd<StrictlyPositiveFinite> for PositiveFinite {
    fn partial_cmp(&self, other: &StrictlyPositiveFinite) -> Option<std::cmp::Ordering> {
        // TODO: compare the internal repr
    }
}
```

**Comment by wcarmon** [comment]
Similar case:

```rust
let a: NonNaNFinite = ...
let b: PositiveFinite = ...

let larger :NonNaNFinite = typed_floats::Max::(a, b)
```

**Comment by tdelmas** [comment]
> comparing typed_floats to std f64 or f32

That's an interesting idea, and it is possible to implement it. I will explore it.

> Comparing to other typed_floats

I agree, and I will explore that too.

**Comment by tdelmas** [comment]
The PR https://github.com/tdelmas/typed_floats/pull/119 implement `PartialOrd` between all typed_floats, and between them and floats.

Do you have an opinion on it?
