### ISSUE TITLE
Constant for 1

### ISSUE THREAD

**Issue by wcarmon** [tdelmas/typed_floats#102]
It appears you have provided lots of common & helpful constraints here: https://github.com/tdelmas/typed_floats/blob/main/typed_floats/src/lib.rs

May we have a constant for `1.0`

Justification:
1. Very common in domains like finance where you model percentages as float between zero and one.
2. Common in machine learning, where you set weights on neural networks, again between zero and one.
3. Without a constant, we have to handle the (impossible) error when building a NonNaN, NonNaNFinite, NonZeroNonNaN, NonZeroNonNaNFinite, Positive, PositiveFinite, StrictlyPositive, StrictlyPositiveFinite
4. One is pretty important in math, like in general

**Comment by wcarmon** [comment]
Hm... I guess since you `impl From<u32> for PositiveFinite<f64>`, there might be a trivial way to do this with `into()`

**Comment by tdelmas** [comment]
The same problem exists with https://doc.rust-lang.org/std/num/struct.NonZeroU64.html : 
https://stackoverflow.com/questions/66838439/how-can-i-safely-initialise-a-constant-of-type-nonzerou8

The constants declared in this lib are the one available on native floats.

I don't think that adding more `const` is interesting for now (but another lib could do it!). I would prefer a more generic solution for that problem.

**Comment by wcarmon** [comment]
Reasonable

**Comment by tdelmas** [comment]
Could I have your opinion on https://github.com/tdelmas/typed_floats/pull/106/files#diff-c7159040dc57dcc3abd41abdfbf6a684815bd2d55e4211cba64f27acb544822c ? 

```
/// Macro to create a constant with a positive value.
/// The resulting constant will be of type `StrictlyPositiveFinite`.
/// Will panic at compile time if the value is not a valid.
///
/// # Examples
///
/// ```
/// # use typed_floats::*;
/// const X: StrictlyPositiveFinite = positive_const!(1.0); // f64
/// const Y: StrictlyPositiveFinite<f64> = positive_const!(f64, 2.0);
/// const Z: StrictlyPositiveFinite<f32> = positive_const!(f32, 3.0);
/// ```
```

**Comment by wcarmon** [comment]
Love the idea!

I gave feedback inline.

I'm not qualified to comment on the rust macro code.

I added comments to the examples as "requirements & API feedback"

**Comment by wcarmon** [comment]
just had a thought ... might not be possible... 

```
const v1: StrictlyPositiveFinite = coerce!(1.0); // f64
const v2: PositiveFinite<f64> = coerce!(2.0);
const v3: NegativeFinite<f32> = coerce!(-3.1);
```

... meaning the macro tries to build whatever type is on the left, if possible.

It still makes sense to accept type as macro param when we cannot auto-derive.

maybe `coerce` is a bad name ... naming things is hard :-)

**Comment by wcarmon** [comment]
Personally, I'd rather use your original instead of specifying the type twice.

**Comment by tdelmas** [comment]
So maybe I should improve and make public the other macro : 
```rust
macro_rules! generate_const {
    ($name:ident, $type:ident, $x:expr, $doc:expr) => {
        #[doc = $doc]
        pub const $name: $crate::StrictlyPositiveFinite<$type> = $crate::positive_const!($type, $x);
    };
}
```

To allow to use it like that : `generate_const!(PI, StrictlyPositiveFinite, f64, 3.14, "The value of PI");`

**Comment by tdelmas** [comment]
(I've go with `positive_finite` because I imagine `negative_finite`, as consts for Infs and Zeros already exists)

**Comment by tdelmas** [comment]
I've improved the API: https://github.com/tdelmas/typed_floats/pull/106#issue-2151782157

I still need to check the soundness of it, but I'm fairly satisfied with the result.
