### ISSUE TITLE
Defaults where sensible

### ISSUE THREAD

**Issue by wcarmon** [tdelmas/typed_floats#93]
Excellent library!

May we have defaults (where sensible), in the same way that rust `f64` [`impl Default`](https://doc.rust-lang.org/std/primitive.f64.html#impl-Default-for-f64)

# Example code change:
```rust
impl Default for PositiveFinite {
    fn default() -> Self {
        PositiveFinite::new_unchecked(0.0)
    }
}

impl Default for NegativeFinite {
    fn default() -> Self {
        NegativeFinite::new_unchecked(-0.0)
    }
}
```

# Related sources
- https://github.com/tdelmas/typed_floats/blob/main/typed_floats/src/types/f32/positive_finite.rs
- https://github.com/tdelmas/typed_floats/blob/main/typed_floats/src/types/f32/negative_finite.rs

And yes, I understand some types lack a sensible default (eg. `StrictlyPositive`)

**Comment by tdelmas** [comment]
Thank you for that suggestion. Do you want to review the corresponding pull request https://github.com/tdelmas/typed_floats/pull/95 ?

**Comment by tdelmas** [comment]
`0.7.4` was just release with that change: https://docs.rs/typed_floats/0.7.4/typed_floats/index.html?search=Default
